### PR TITLE
Test and Refactor Multiple Adapter logic

### PR DESCRIPTION
**Pull request by tjwebb**
- added multiple adapter tests that clarify the functionality and increase coverage
- refactored dictionary builder to use lodash
- added comments to dictionary builder

### CODE REVIEW

**Comment by devinivy** [comment]
This looks good.  The `_build` method is nifty–I wonder if it's also a little dense?

**Comment by tjwebb** [comment]
Yea, although it took me awhile to figure out what the other method was doing as well -- for me at least, it wasn't as obvious as it seemed. I decided to condense, remove a bunch of local variables that don't do anything, and just tried to clarify what's actually going on in the comments.

**Comment by tjwebb** [comment]
also I'm pretty sure that `cloneDeep` was just silliness. It's just an array of strings.

**Comment by tjwebb** [comment]
Ok @devinivy per your suggestion I found some room for improvement. I removed `_.partial` and `_.identity` so that human beings can actually read it.

**Comment by dmarcelino** [comment]
Looks good :white_check_mark:

**Pull request merged**
