### PR TITLE
Through association id datetime (try 2).

### PR DESCRIPTION
**Pull request by elennaro**
Second try to resolve Issue  #1265.

I've refactored the part like this:

```
...
if (record instanceof Date) {

      var item = new Date(record);
      _.extend(item.__proto__ , record.__proto__);

      this.object[association] = item;

      // _.isObject() does not match null, so we're good here.
    }
...
```

The question is do we need `_.extend(item.__proto__ , record.__proto__);` or it has no sense here, since no one extends Date with custom methods?

@particlebanana 
I'll fix and rewrite anything you say.

Thanks for your patience and care.
I never committed to such a big and serious enterprise projects, so I feel a little nervous :)

### CODE REVIEW

**Comment by particlebanana** [comment]
@elennaro hey don't be worried! We'll get it figured out and merged in. I'll try and take a look at this later today. Thanks for your work!

**Comment by elennaro** [comment]
@particlebanana thanks a lot!
You guys are wonderful!

**Comment by elennaro** [comment]
I so sorry to bother you. 
But we need some fix for Issue #1265 to be able to update from 0.10.27.

If you don't like something in this PR, I will rewrite it as you say.

**Comment by particlebanana** [comment]
Ok @elennaro this one looks good. I think using dates as primary keys is a horrible solution but making sure it doesn't crash is more important. Thanks for the work, I'll get a patch published shortly.

**Comment by elennaro** [comment]
@particlebanana thank you vary much! You saved our day!
You're totally right about date as PK :)

**Pull request merged**
