### PR TITLE
Add `.pick()` and `.omit()` methods

### LINKED ISSUE #73: .select()
Support for both sorts of usages:

Traditional `SELECT`:
````javascript
User.find().select('name', 'age').exec(cb);
User.find().select(['name', 'age']).exec(cb);
````

`Prune` is an exclude (inverse of select)
````javascript
User.find().prune('password', 'apiKey').exec(cb);
User.find().prune(['password', 'id']).exec(cb);
````

### PR DESCRIPTION
**Pull request by dmarcelino**
This PR is the same as #509, but targeting `0.11`, props to @jasonsims. Please check #509 for the full discussion.

Original message:

> This PR adds the ability to apply projections to waterline queries. It's an extension of the work accomplished in  #162 by adding flexibility for how selection arguments are supplied as well as exclusions via `.omit()`. With this change, the adapters will always receive a standardized selection criteria object which they can process as needed for their specific query language. Here's an example of this object:
> ```js
> // User.find().pick('name', 'age').exec(cb);
> { where: null, pick: { name: 1, age: 1 } }
> 
> // User.find().omit('name', 'age').exec(cb);
> { where: null, omit: { name: 0, age: 0 } }
> ```
> 
> Usage examples:
> ```js
> // Include only 
> User.find().pick('name', 'age').exec(cb);
> User.find().pick(['name', 'age']).exec(cb);
> User.find().pick({name: 1, age: 1}).exec(cb);
> 
> // Exclusion
> User.find().omit('name', 'age').exec(cb);
> User.find().omit(['name', 'age']).exec(cb);
> User.find().omit({name: 0, age: 0}).exec(cb);
> ```
> 
> fixes #73

cc: @clarkorz, @mikermcneil, @mdunisch, @particlebanana, @sskyy, @devinivy, @tjwebb

### CODE REVIEW

**Comment by dmarcelino** [comment]
#73 actually asks for a `.select()` method so we should probably follow @devinivy's suggestion on https://github.com/balderdashy/waterline/pull/509#issuecomment-86695959:
> I think `pick` and `select` should be aliases.

**Comment by tjwebb** [comment]
re: http://stackoverflow.com/a/29769995/291180

@dmarcelino would you mind adding a quick sentence or two in the docs about how the `select` criteria works?

**Comment by dmarcelino** [comment]
@tjwebb, I can't believe you didn't know about it... to be honest I don't remember how I found out it existed. Sure, I'll look into adding it.

**Comment by tjwebb** [comment]
>  to be honest I don't remember how I found out it existed. Sure, I'll look into adding it.

Yea I sort of knew about it, but I've never used it and didn't really know the API. Is it unit tested?

**Comment by dmarcelino** [comment]
I don't think it is, there are some tests that use it ([quick search](https://github.com/balderdashy/waterline/search?utf8=✓&q=select)) but no particular unit test to explicitly test it.

**Comment by zfrenchee** [comment]
Why isn't this a feature yet?

**Comment by weyert** [comment]
Any news on this?

**Comment by randallmeeker** [comment]
closed w/o comment?

**Comment by chacliff** [comment]
personally i think that this should be structured just like mongo structures it... if your going to use "select" or "pick"... not omit it should just be <field>: 0 || 1, where 0 is to omit, and 1 is to include. by default if no selection is made everything is included. by default if a field is marked with 1 ID is still included unless explicitly marked 0.

**Pull request closed without merging**
