### PR TITLE
add quotes to ROOT variable and ignore coverage folder

### PR DESCRIPTION
**Pull request by dpsutton**
I know this is a simple change, but I'm new to the project and was looking through the tests. The Makefile was breaking for me because I keep all of my work in "Google Drive". The soft link was failing to create, which caused the require statement in the waterline-adapter-tests to fail when requiring the linked version of waterline. The quotes make sure that the pwd output is respected in the softlink.

The other minor change is simply adding the coverage/ folder to the gitignore

### CODE REVIEW

**Comment by devinivy** [comment]
Seems okay to me :+1:

**Comment by dmarcelino** [comment]
@dpsutton, when comparing the description against the changes in this PR it seems you've unintentionally added more commits to your branch. I suggest using feature branches to keep changes isolated.

**Comment by dpsutton** [comment]
Yeah, I accidentally used the same branch for a refactoring pass as well. What's the best way to remedy this? Should I cherry pick the intended commit into its own branch and resubmit a pull request while canceling this one?

**Comment by particlebanana** [comment]
Hey @dpsutton I pulled these changes out https://github.com/balderdashy/waterline/pull/1279

**Pull request closed without merging**
