### PR TITLE
Lint Rule Cleanup (continuation of #1070)

### PR DESCRIPTION
**Pull request by IanVS**

### CODE REVIEW

**Comment by dmarcelino** [comment]
I love these linting PRs! :grinning: 

All looks good to me :white_check_mark:

**Comment by IanVS** [comment]
This is all I can do for now until some decisions are made on #1070.

**Comment by IanVS** [comment]
Getting closer.  Here is the current status:

screenshot from 2015-07-10 00 42 38

**Comment by dmarcelino** [comment]
@devinivy, what is your opinion?

@IanVS, regarding the linting rules with < 10 warnings I think we can adhere to the eslint default since we are close to it anyway.

**Comment by devinivy** [comment]
I voted on that other thread.  Also, I agree with @dmarcelino .  I'd like to also get `no-unused-vars` in there too, if it's not too hard.

**Comment by IanVS** [comment]
I agree that `no-unused-vars` should be set.  I'm a little nervous about going in and removing them mysekf, since that is a more drastic change than the formatting changes I've been making.  The changes that can have an impact on execution and have the possibility of breaking things, I'd rather leave to the waterline team to correct.

**Comment by devinivy** [comment]
Makes sense!  What's the easiest way to hone-in on a single rule?  I saw in the other branch you have something like `npm run nibble`?

**Comment by IanVS** [comment]
Yes, in fact you should be able to use that on the master branch now, since the other PR was merged.  Make sure you `npm install` to refresh and pull in the latest version of it, (`0.1.1`) because there was a bug prior to that.  Let me know if you try to use it and have trouble.

**Comment by dmarcelino** [comment]
@IanVS, are you submitting new commits to this branch? If not, @devinivy are you OK we merge it?

During this transition stage to adopting eslint causes several broad changes and is likely to create merge conflicts on other PRs, so the quicker we do it, the quicker we'll get back to business as usual! :grinning:

**Comment by IanVS** [comment]
I was waiting to hear if the style decisions were final. If there is consensus around https://github.com/balderdashy/waterline/pull/1070#issuecomment-120492271 I can make another commit or two to this PR and then it will be up to you all to fix the last few rules. Can probably finish tomorrow night, if that works for you.

**Comment by dmarcelino** [comment]
My question was more towards finding out if you are adding commits to this PR or making additional PRs, not trying to pressure you in any way. :) Just trying to mitigate the scenario where concurrent PRs generate merge conflicts.

**Comment by IanVS** [comment]
I was planning to continue committing to this branch, but if you want to merge and have me open another that's fine too. Just let me know how to proceed.

**Comment by dmarcelino** [comment]
I think we can proceed with https://github.com/balderdashy/waterline/pull/1070#issuecomment-121018029:

> no-multiple-empty-lines: 2
> space-after-keywords: always
> space-before-function-paren: never
> no-undef: true
> new-cap: true
> no-proto: true
> eqeqeq: true - smart
> no-new: true

unless someone disagrees.

**Comment by IanVS** [comment]
@dmarcelino If all are happy so far, I would recommend merging at this point.  The rest of the changes are a little more "dangerous" So I'd feel more comfortable doing them in another PR.  The number of errors right now is down to a fairly manageable 73:

screenshot from 2015-07-14 00 56 32

**Comment by devinivy** [comment]
:+1: horray!  Nicely done :)  That makes sense.  I'll see if I can help with some of the remaining warnings in a separate branch.  Anyone else in to tackle this?

**Comment by dmarcelino** [comment]
Thanks @IanVS!

**Pull request merged**
