### PR TITLE
Allowing types to be defined in each adapter

### PR DESCRIPTION
**Pull request by shekhei**
Continuing #827 here, original text:

> I do think this is quite important, there are cases where supported types might be a bit different with each adapter.
> 
> With this change, this will allow each adapter to extend and create their own supported types.
> 
> Although this might mean that it becomes more difficult to have models that supports all sorts of different adapters, the chances of the models changing adapter is rather low, this change can make waterline more extensive :)

### CODE REVIEW

**Comment by dmarcelino** [comment]
For reference, this fixes #819 and relates to #665.

**Comment by dmarcelino** [comment]
@shekhei, can you post examples on how this would work? I guess this would also require changes on the adapters to actually support the non compliant (by waterline standards) types, right?

**Comment by shekhei** [comment]
Basically, you can see it here
https://github.com/eskygo/sql-layer-adapter-sails/blob/master/lib/adapter.js#L62
If it is not defined, the default list is used, if this function is defined, it will result in a union of the default set and the returned set, combined with
https://github.com/eskygo/sql-layer-adapter-sails/blob/master/lib/adapter.js#L62
which allows it to be translated to actual types.

There should be no changes required for the current adapters.

**Comment by dmarcelino** [comment]
Well, for an adapter to extend the waterline supported types it would need to implement `.supportsType(type)`, that was the bit of information I was after.

Any sort of validation would also be the adapter's responsibility and this change does not prescribe a way to do it, which is also something we should consider...

I do agree we need to provide a way for adapters to extend the supported types, I'm not 100% sure this is the best way. Ideally I would like to see something that would also offer validation support consistent with the current waterline validations (not sure if possible).

@devinivy, @tjwebb, @particlebanana, what do you think of this?

**Comment by shekhei** [comment]
@dmarcelino absolutely agree that this method isn't exactly the most robust method. perhaps another way would be to allow types to be "defined". the current type mechanism in waterline seem to be only used for "type matching" and "DDL translation". 

A better way might be to do something similar to, perhaps mongoose where type definition are objects? But of course that will require quite a bit of change.

**Comment by dmarcelino** [comment]
@shekhei, I've just stumbled upon PR #72 which reads custom types from collection and this got me thinking... what if we extend this so waterline core reads custom types from the adapter? The idea would be, in adapter.js we would optionally add a `types` object like:
``` javascript
  //custom types
  types:{
     geoJSON: isGeoJSON_function
  },
```

If present waterline core would read it and apply those extra custom types. That way we would satisfy both the schema and validation sides of this problem.

What do you think?

**Comment by shekhei** [comment]
That sounds good! 

This "type object" would probably end up being something complex though, any thoughts on that? I've seen how mongoose does it, very robust, but it gets rather complex quickly.

https://github.com/Automattic/mongoose/blob/master/lib/types/array.js

**Comment by dmarcelino** [comment]
I guess that would be a "problem" for each adapter to solve but we can follow anchor's [rules.js](https://github.com/balderdashy/anchor/blob/master/lib/match/rules.js) where the functions are actually defined in a different file.

**Comment by shekhei** [comment]
Any examples on how you reckon it would end up looking like? Perhaps for a standard type that's already supported?

**Comment by dmarcelino** [comment]
Anchor is what waterline uses under the covers, take a look at: https://github.com/balderdashy/anchor/blob/master/lib/match/rules.js#L55

**Comment by dmarcelino** [comment]
@shekhei, take a look at #977, I think it's the best way to address this. What do you think?

**Comment by dmarcelino** [comment]
Note, PR #977 was replaced by #981.

**Comment by dmarcelino** [comment]
Closing this in favor of #981.

**Pull request closed without merging**
