### PR TITLE
prevents infinite recursion in "WLError.stack" setter

### PR DESCRIPTION
**Pull request by shaunc**

### CODE REVIEW

**Comment by dmarcelino** [comment]
Hi @shaunc, thanks for this. I'm assuming this is the fix for #1001?

**Comment by shaunc** [comment]
yes ... I am only assuming that "rawStack" is what should be set -- this "works for me" but don't know what users of setters really expect. (OTOH not documented so why not this? :))

**Comment by dmarcelino** [comment]
@tjwebb, can you give a glance at this? This fixes #1001 which was caused by PR #920.

>  (OTOH not documented so why not this? :))

Very true :)

**Comment by dmarcelino** [comment]
@devinivy, what do you think?

**Comment by devinivy** [comment]
I think it's fine!

**Comment by dmarcelino** [comment]
Closing this over PR #1061 which includes @shaunc's fix plus a failing test.

**Pull request closed without merging**
