### PR TITLE
Allow calling save on an unpersisted record

### PR DESCRIPTION
**Pull request by ejlangev**
First pass on an implementation of https://github.com/balderdashy/waterline/issues/763.  Seems pretty simple but might be totally wrong.  Let me know if it is so I can correct.  @devinivy

### CODE REVIEW

**Comment by ejlangev** [comment]
Also this is probably against the incorrect branch.  If so let me know what branch it should be against so I can fix.

**Comment by particlebanana** [comment]
Hey @ejlangev can you spec out in a comment exactly what the API looks for using this?

**Comment by ejlangev** [comment]
```js
var record = new MyModel({ a: 1, b: 'a' });
return record.save()
  .then(function() {
    // Do something after the save if necessary
  })
```

**Comment by shvelo** [comment]
Does this add support for `new MyModel()`?

**Pull request closed without merging**
