### PR TITLE
Refactor WLError, set stack writable

### LINKED ISSUE #913: WLError getter for "stack" breaks bluebird
https://github.com/balderdashy/waterline/blob/master/lib/waterline/error/WLError.js#L146-L148

see https://github.com/petkaantonov/bluebird/issues/552

Bluebird needs to be able to set the `.stack` property on `WLError` but is unable to do so

### PR DESCRIPTION
**Pull request by tjwebb**
- resolves #913 
- Includes some other minor cleanup

### CODE REVIEW

**Comment by devinivy** [comment]
Haven't tested this out, but it appears to be good!

**Comment by tjwebb** [comment]
I'm using it locally now; the bug is gone, and I've noticed no other issues.

**Comment by dmarcelino** [comment]
I'm good with this! :white_check_mark:

**Comment by dmarcelino** [comment]
@tjwebb, it seems this fix is causing infinite loops when setting stack on WLError. Can you take  a look at #1001? Thanks.

**Pull request merged**
