### PR TITLE
#887: Refuse to run alter/drop migration strategies in production.

### PR DESCRIPTION
**Pull request by dmarcelino**
Addresses issue #887.

### CODE REVIEW

**Comment by devinivy** [comment]
Sweet– can we also change the default strategy on production to `"safe"` and submit a PR to waterline-adapter-tests that would go up with this PR in tandem?

**Comment by dmarcelino** [comment]
Hey @devinivy, I've tried changing the default to `'safe'` in my machine but it breaks the waterline-adapter-tests. I've mentioned that here: https://github.com/balderdashy/waterline/issues/887#issuecomment-84332762

**Comment by devinivy** [comment]
Yup– that's why I'm suggesting we also submit a PR to waterline-adapter-tests that will allow the change to occur without breaking any tests.  Or are you saying that we should not change the adapter tests to cater to this PR?

**Comment by dmarcelino** [comment]
Ah, I see what you mean now, sorry. That should be the way to do it but honestly I haven't yet looked at what needs to be changed in `waterline-adapter-tests`. I suppose several fixtures need to be changed to `migrate: 'alter'`. For I now I would prefer to keep this PR and the `migrate: 'safe'` default as different PRs as they can be merged independently.

**Comment by devinivy** [comment]
Good enough for me!  It would be great if we could work to have the adapter tests, docs, and default migration strategy all updated soon after this PR goes through.

**Comment by dmarcelino** [comment]
Agreed! And stage 2 of that would be to discuss the future of migrations (both automated (dev) and manual(manual)). There are some interesting API ideas but they never developed on them, check this:
https://github.com/balderdashy/sails-docs/blob/master/contributing/adapter-specification.md#migratable-interface

**Comment by dmarcelino** [comment]
Thanks @tjwebb!

**Pull request merged**
