### PR TITLE
[patch] fixing update method so that it takes into account a string for the a…

### PR DESCRIPTION
**Pull request by jenjenut233**
…utoUpdatedAt attribute (was not updating the database record with the current timestamp)

### CODE REVIEW

**Comment by jenjenut233** [comment]
fixed

**Comment by joshuamarquez** [comment]
same problem here

**Comment by particlebanana** [comment]
Thanks @jenjenut233!

**Comment by particlebanana** [comment]
Published Waterline `0.11.3` to Waterline (for use with Sails) and will publish a new version of `0.12` in a bit.

**Pull request merged**
