### PR TITLE
Support embeddable association (denormalization)

### PR DESCRIPTION
**Pull request by clarkorz**
With certain commits in `waterline-schema` and `sails-mongo`,
association can be set to embeddable using `embed` keyword. And if so,
the associating model can be fully or partially embedded. This is
denormalization, and only works with `sails-mongo` currently.

https://github.com/balderdashy/waterline/issues/427

### CODE REVIEW

**Comment by leobudima** [comment]
Would be absolutely great if we could push this through!

**Comment by arxpoetica** [comment]
For anyone wondering what this all means, here's some light reading: http://blog.mongodb.org/post/87892923503/6-rules-of-thumb-for-mongodb-schema-design-part-2

**Comment by elennaro** [comment]
+1 for this

**Comment by particlebanana** [comment]
Hey @clarkorz thanks for your time on this. I know it's been sitting here for a while and that's mainly because I felt guilty closing it after the time that went into it. Now it's been sitting long enough that it can't be merged.

I have denormalization on the roadmap. It's something I would like to see a full spec on, especially how deep querying could work but it just doesn't fit into the project right now.

If anyone feels very passionately about this and wants to write up a spec based on the [Contribution Guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements) that would be great!

**Pull request closed without merging**
