### PR TITLE
Prevents infinite recursion in "WLError.stack" setter

### LINKED ISSUE #1001: Setting stack on WLError causes infinite loop
Seems to have been introduced with the recent fix for this issue: https://github.com/balderdashy/waterline/issues/913

WLError.stack is set to itself in the setter, causing an infinite loop
```javascript
Object.defineProperties(WLError.prototype, {
  stack: {
    enumerable: true,
    get: function () {
      return util.format('Error (%s) :: %s\n%s', this.code, this.reason, this.rawStack);
    },
    set: function (value) {
      this.stack = value; // Infinite loop?
    }
  }
/// Snip
});
```

When I cause a WLValidationError, the server crashes with this error:
```
sails/node_modules/waterline/lib/waterline/error/WLError.js:129
verbose:     set: function (value) {
                  ^
verbose: RangeError: Maximum call stack size exceeded
    at WLValidationError.Object.defineProperties.stack.set [as stack] (sails/node_modules/waterline/lib/waterline/error/WLError.js:129:19)
    at WLValidationError.Object.defineProperties.stack.set [as stack] (sails/node_modules/waterline/lib/waterline/error/WLError.js:130:18)
    at WLValidationError.Object.defineProperties.stack.set [as stack] (sails/node_modules/waterline/lib/waterline/error/WLError.js:130:18)
    at WLValidationError.Object.defineProperties.stack.set [as stack] (sails/node_modules/waterline/lib/waterline/error/WLError.js:130:18)
(... snip about 50x more ...)
```

### PR DESCRIPTION
**Pull request by dmarcelino**
Fixes #1001.

The PR replaces PR #1045, the only difference being that it includes a failing test proving @shaunc's fix does indeed fix the issue.

@particlebanana, @devinivy, please take  a look.

### CODE REVIEW

**Comment by dmarcelino** [comment]
Running the unit without the fix causes a `RangeError: Maximum call stack size exceeded` just like reported in #1001.

**Comment by devinivy** [comment]
Will we make an analogous fix to the `message` property?

**Comment by dmarcelino** [comment]
Give me a minute... :clock1:

**Comment by dmarcelino** [comment]
PR #1062, which actually was branched off this branch.

**Comment by dmarcelino** [comment]
Thanks @shaunc!

**Pull request merged**
