### PR TITLE
[fixes #1493] fix incorrect loop

### LINKED ISSUE #1493: Critical Issue: normalize-where-clause strips out incorrect juncts/disjuncts
Hey Guys,

It looks to me like the following loop is incorrect and will remove the incorrect elements from an array if the array has more than one element slated for removal:

[https://github.com/balderdashy/waterline/blob/master/lib/waterline/utils/query/private/normalize-where-clause.js#L602-L608](https://github.com/balderdashy/waterline/blob/master/lib/waterline/utils/query/private/normalize-where-clause.js#L602-L608) <- broken loop

I ran into this issue recently in an application where my queries seemed to get gobbled up and spit out incorrectly after the where clause was normalized.

Essentially, I think the indexes referenced in the `indexesToRemove` array change (in the target array) after the first call to `conjunctsOrDisjuncts.splice(indexToRemove, 1);`

Additionally, the `numRemovedSoFar` variable seems to serve no purpose.

I can refactor this block and issue a pull request, do you concur with this assessment?

**This issue seems urgent as it completely destroys a valid query**

Thanks,
-Mike

**Waterline version**: 0.13.0-rc11
**Node version**: 6.2.0
**NPM version**: 3.6.0
**Operating system**: All

<hr/>

### PR DESCRIPTION
**Pull request by mdconaway**
This commit closes issue #1493.

### CODE REVIEW

**Comment by mdconaway** [comment]
Fixed!

**Comment by mdconaway** [comment]
Ok, I think it's seriously fixed this time sailsbot.

**Comment by mdconaway** [comment]
^ This one seems important: @mikermcneil , @particlebanana

**Comment by sgress454** [comment]
This is fixed as of v0.13.1-1.

**Pull request closed without merging**
