### PR TITLE
Manytomanythrough fix and failling test for #1133

### PR DESCRIPTION
**Pull request by atiertant**
fix and failling test for https://github.com/balderdashy/waterline/issues/1133

### CODE REVIEW

**Comment by weyert** [comment]
Failing??

**Comment by atiertant** [comment]
@weyert this test and fix require https://github.com/balderdashy/waterline-schema/pull/30

**Comment by particlebanana** [comment]
Alright @atiertant everything looks good in master and all tests are passing. I cherry picked these commits into the `0.10.x` stable branch and went ahead and published `0.10.28` to npm.

Thanks again for all your hard work with this! The next thing we need to do is update the docs for `through` with a better explaination of where they stand as of now. Then I would like to look into @devinivy's issue with lifecycle callbacks on through tables.

**Comment by devinivy** [comment]
Brilliant work!

**Comment by dmarcelino** [comment]
Awesome stuff, congrats @atiertant :clap:

**Pull request merged**
