### PR TITLE
[*] fix sub attributes for mongo db

### PR DESCRIPTION
**Pull request by kalyuk**

### CODE REVIEW

**Comment by dmarcelino** [comment]
Hi @kalyuk, please provide some background for this change, is there any open issue for it? If this is MongoDB specific is something that can be done in the [sails-mongo adapter](https://github.com/balderdashy/sails-mongo)?

**Comment by kalyuk** [comment]
The "sails-mongo adapter" do not work because the core of "waterline" does not give an opportunity to validate nested attributes.

We can now make this type of design
older:
{
items: {
type: 'json'
}
}

now 

{
 items: [
   name: {
    type: 'string'
    minLength: 5
}
]
}

This makes it possible to use the possibility of using validation attributes nested "mongodb"
https://github.com/balderdashy/sails-mongo/issues/280

Sorry for my English :)

**Comment by dmarcelino** [comment]
I understand the objective now, I think it is a similar idea to **Support embeddable association (denormalization) #428**. However this is breaking the [automated build](https://travis-ci.org/balderdashy/waterline/jobs/70578684#L9158) with many tests failing so it can't be merged as it stands now.

**Comment by kalyuk** [comment]
I tried to keep backward compatibility

**Comment by dmarcelino** [comment]
Cool, thanks!

**Comment by glebcha** [comment]
I think this PR will resolve https://github.com/balderdashy/sails-mongo/issues/26 and https://github.com/balderdashy/waterline/issues/658 .
But all about tests now.

**Comment by devinivy** [comment]
This seems to break 128 tests, many related to validation.  I wonder if this problem would be more naturally solved by #824.  You could also use `anchor` in a custom validator to achieve a similar effect.

**Comment by kalyuk** [comment]
Run the tests they must pass without problems

**Comment by particlebanana** [comment]
Yes, unfortunately this fails too many checks. We have embededd/denormalized schemas on the roadmap but it's not something that is planned for the immediate future.

**Pull request closed without merging**
