### PR TITLE
Fix special attribute names - aka "type" + failling test

### PR DESCRIPTION
**Pull request by atiertant**
check https://github.com/balderdashy/waterline-schema/issues/22 bug

### CODE REVIEW

**Comment by dmarcelino** [comment]
@atiertant, is this the failing test for balderdashy/waterline-schema#22 / #788?

**Comment by atiertant** [comment]
@dmarcelino yes this test insert 'type' key in transformer

**Comment by dmarcelino** [comment]
Hey @atiertant, I don't think passing a keyword in the function the most elegant solution yet I can't think of any better fix without a significant re-write. This is probably the most efficient fix, I think it's good! :white_check_mark: 

@devinivy, what do you think?

**Comment by dmarcelino** [comment]
@tjwebb, can you please take a look?

**Comment by dmarcelino** [comment]
@devinivy, have you had a chance to look into this?

**Comment by devinivy** [comment]
I think it's okay too.

**Comment by atiertant** [comment]
Hi ! 
Is there something else i could do to correct this bug? 
If code is ok for you, couldn't you merge it?
or should i modify something in my code?

**Comment by dmarcelino** [comment]
@particlebanana, can you take a look please? Both me and @devinivy are OK with this.

**Comment by particlebanana** [comment]
Yeah this looks great. Closing https://github.com/balderdashy/waterline-schema/issues/22 as well

**Pull request merged**
