### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by listepo**

### CODE REVIEW

**Comment by particlebanana** [comment]
The lodash update is a biggie. We need to walk through that one. Some more discussion here: https://github.com/balderdashy/waterline/pull/837

**Comment by tjwebb** [comment]
#837 is more of a broad refactor aimed at migrating some bare-metal looping craziness into lodash. This PR just upgrades some stuff

**Comment by devinivy** [comment]
So someone can say confidently that the `lodash` and `should` major version upgrades are safe?
https://github.com/lodash/lodash/wiki/Changelog#v300
https://github.com/shouldjs/should.js/wiki/Breaking-changes#changes-for-5x

**Comment by particlebanana** [comment]
The lodash 3.0 major version was a big one. If the tests pass then it *should* be good but needs some QA. No idea about the should upgrade.

**Comment by dmarcelino** [comment]
Any updates on this?

**Comment by particlebanana** [comment]
Manually merged for the lodash dependency. Thanks @listepo and sorry this took so long!

**Comment by dmarcelino** [comment]
Dependencies are now green, good stuff!

**Pull request merged**
