### PR TITLE
#887: change default migration to 'safe'

### LINKED ISSUE #887: migrate: 'alter' when using Waterline standalone
I got bitten by this gotcha and lost (development) data...

I and some others on gitter chat think default should be `migrate: 'safe'`

https://github.com/balderdashy/waterline/blob/63effdb480ae9bd61cd78fd534e1e513294bd98d/lib/waterline/collection/defaults.js

@dmarcelino edit: this issue has been split into 2 parts (check the below [comment](https://github.com/balderdashy/waterline/issues/887#issuecomment-84045351)):
 - [x] Prevent users from using alter/drop in production by throwing an error. That way they can fix their config: #893
 - [ ] Change default migration to `'safe'` (or `'create'`)

### PR DESCRIPTION
**Pull request by dmarcelino**
Fixes #887.

Depends on balderdashy/waterline-adapter-tests#50 or the integration tests will be broken.

### CODE REVIEW

**Comment by devinivy** [comment]
:heavy_check_mark: looks good!

**Comment by tjwebb** [comment]
The tests are already broken in balderdashy/waterline-adapter-tests#50. Should I merge that anyway?

**Comment by dmarcelino** [comment]
Looks like you've merged already... @tjwebb, the waterline-adapter-tests always fail because of issues in sails-postgresql (balderdashy/waterline-sequel#43), sails-mongo (balderdashy/sails-mongo#260), sails-mysql (https://github.com/balderdashy/waterline/issues/887#issuecomment-95210555) and sails-redis (this one will take more than 1 issue to fix).

The reason for not merging before balderdashy/waterline-adapter-tests#50 is that this is going to break (additional) integration tests on schemaful adapters.

**Comment by particlebanana** [comment]
Just for posterity we need to look into sails and see if it relies on the default being alter. We should set it in sails so that it doesn't matter what the default here is but I'm not sure that's being done.

Either way lets be safe in get this in 0.11. Thanks everyone!

**Pull request merged**
