### PR TITLE
modify toObject so that you get a POJO back

### PR DESCRIPTION
**Pull request by particlebanana**
this *should* help with the recursion issues and solve #891

### CODE REVIEW

**Comment by particlebanana** [comment]
call stack issues here https://github.com/balderdashy/sails/issues/2813 and https://github.com/balderdashy/sails/pull/2647

**Comment by devinivy** [comment]
Will look over this asap, but at a very cursory glance this seems okay to me.  Someone said that this could affect blueprints with the socket hook in sails (https://github.com/balderdashy/waterline/issues/891#issue-62683601).  I'd rather that issue not hold this bug up, but I'm just wondering if it's being addressed.

**Comment by particlebanana** [comment]
I have that PR out in Sails which is a workaround in the hook but this should fix that up unless I misunderstood the sails issue.

**Comment by dmarcelino** [comment]
This will probably also fix #317.

@particlebanana, can't see anything wrong with this :white_check_mark:

**Comment by devinivy** [comment]
From the tests it looks like associations are maintained, which was my only concern.  Seems okay!

**Comment by dmarcelino** [comment]
I only have one minor concern... in the below line:
``` javascript
var _obj = JSON.parse(JSON.stringify(this.object));
```
an error will be thrown if the object has any circular references. While circular references are not allowed in JSON we will be limiting `toObject()` with the same constraint. Not huge as many adapters don't return circular references and in, many cases, they are not desired because the next move is usually to jsonfy the object.

**Comment by particlebanana** [comment]
Ok thanks guys, gonna pull this in and do some real world testing. @dmarcelino as for the circular references, technically you could handle that without ever calling toObject - or more likely before. The default model behavior is to call this before stringifying it and sending to the client so it should help clear up a lot of issues. Let's cross the circular ref issue when/if it comes up.

**Comment by dmarcelino** [comment]
> Let's cross the circular ref issue when/if it comes up.
Agreed!

**Pull request merged**
